# Thumbnail CAM should be added in integrations -> Generic Camera
# Please change the IP of your printer
# URL: http://10.0.0.8:7125/server/files/gcodes/{{ states('sensor.vcore400_url_thumbnail') }}
# RTSP transport protocal:
#   - don't select anything
# Authentication
#   - Select -> Basic
# the rest keep it default

# RaspBerryPi CAM should be added in integrations -> MJPEG IP CAMERA
# Please change the IP of your printer
# MJPEG URL: http://10.0.0.8/webcam/?action=stream
# Still image URL: http://10.0.0.8/webcam/?action=snapshot
# the rest keep it default
